version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
